version: '2'
services:
    rfbloyalty-app:
        image: volthier/rfbloyalty
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://rfbloyalty-postgresql:5432/rfbloyalty
            - JHIPSTER_SLEEP=10
        ports:
            - 8080:8080
    rfbloyalty-postgresql:
        image: postgres:10.4
        environment:
            - POSTGRES_USER=rfbloyalty
            - POSTGRES_PASSWORD=
    
