version: '2'
services:
    rfbloyalty-app:
        image: rfbloyalty
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://rfbloyalty-postgresql:5432/rfbloyalty
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rfbloyalty-postgresql:
        extends:
            file: postgresql.yml
            service: rfbloyalty-postgresql
