version: '2'
services:
    rfbloyalty-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/rfbloyalty/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=rfbloyalty
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
